### ISSUE TITLE
Automation Servers Degradation + Remote Logging is Harming Performance

### ISSUE THREAD

**Issue by ExpandedVenture** [ExpandedVenture/ConnectionSphere#149]
# Analysis
1. Deprecate `RemoteLogger` and use SSH to show log files anywhere instead.
2. Use logs to research the cause of the degradation.

**Comment by ExpandedVenture** [comment]
> 1. Deprecate `RemoteLogger` and use SSH to show log files anywhere instead.

Done with this.

1. Use SSH to connect the server.
2. Use `nano` to open the log file.
3. USe `ALT+/` to jump the the end of the logifle with `nano`.

**Comment by ExpandedVenture** [comment]
Here is the log of a job that failed, and kept the browser opened instead of closing it:

```bash
nano GAUSS07.00-50-56-24-6B-5C.unicorn13.log
```

```
2021-12-02 22:24:02: Reporting login failure (unknown): Net::ReadTimeout
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in `get'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/navigation.rb:30:in `to'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:77:in `goto'
/home/bots/.rvm/gems/ruby-2.2.4/gems/stealth_browser_automation-1.2.41/lib/browserfactory.rb:414:in `goto'
/home/bots/.rvm/gems/ruby-2.2.4/gems/bots-1.2.106/lib/linkedin/bots/LinkedInProfile.rb:27:in `scrape'
/home/bots/code/tempora/lib/prospecting/process.rb:1260:in `block in process'
/home/bots/code/tempora/lib/prospecting/process.rb:1233:in `each'
/home/bots/code/tempora/lib/prospecting/process.rb:1233:in `process'
/home/bots/.rvm/gems/ruby-2.2.4/gems/pampa_workers-1.1.32/lib/myremoteprocess.rb:106:in `run'
/home/bots/.rvm/gems/ruby-2.2.4/gems/stealth_browser_automation-1.2.41/lib/browserfactory.rb:243:in `run'
./p/bots.prospecting.rb:32:in `<main>'... done (with no screenshot)
2021-12-02 22:24:03: Tracking bot error... done (with no screenshot)
2021-12-02 22:24:03: Destroy any browsers... done
2021-12-02 22:24:08: Ping to Division... done
2021-12-02 22:24:08: Release lnuser... done
2021-12-02 22:24:08: Run garbage collector... done
2021-12-02 22:24:08: Update from central (2)... done
2021-12-02 22:24:09: Update worker (2)... done
2021-12-02 22:24:09: Sleep... done
```

**Comment by ExpandedVenture** [comment]
Email sent to Multilogin:

> See the picture below.
> 
> The browser got freeze, and the only way to close it is by killing the process.
> 
> I am doing automation, so I close the browser from software.
> 
> How can I get the PID of a Mimic browser in order to kill the process?
> 
> ![image](https://user-images.githubusercontent.com/87434466/144611715-1021bff6-675f-4af1-b249-6d77f967bf43.png)
>

**Comment by ExpandedVenture** [comment]
Email sent to Multilogin

> I have an idea:
> 
> Can you share with me a linux command to kill properly all the mimic processes started XX minutes ago?

**Comment by ExpandedVenture** [comment]
Reply from Multilogin:

> One option you could try out is below:
> kill $(ps -eo comm,pid,etimes | awk '/^chrome/ {if ($3 > 60) { print $2}}')
> 
> Where the process name is chrome and 60 is the timeout in seconds. All the chrome (Mimic) processes that have been running longer will be killed. That said, I would not guarantee that this is the best solution. Might be better to create a specific bash script instead. Unfortunately, this is bit out of the range of our support.
> 
> Hope this helps.

**Comment by ExpandedVenture** [comment]
Here is the query to get the full list of servers that are running automation:

```sql
select distinct h.id, h.net_hostname
from host h
join worker w on ( h.id=w.id_host and w.assigned_process like './p/bots.%.rb' and w.last_ping_time > dateadd(hh, -1, getdate()) )
order by h.net_hostname
```

**Comment by ExpandedVenture** [comment]
The kill command is running.
The performance of servers are stable.

Sometime, the command starts failing with this error:

```
2021-12-20 11:58:23: kill abandoned browsers...
2021-12-20 11:58:24:  > GAUSS07... done (sh: 1: kill: Usage: kill [-s sigspec |
-signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
)
2021-12-20 11:58:24:  > GAUSS08... done (sh: 1: kill: Usage: kill [-s sigspec |
-signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
....
```
