### ISSUE TITLE
Failure to resolve SMS verification on signup.

### ISSUE THREAD

**Issue by leandrosardi** [ExpandedVenture/ConnectionSphere#258]
1. Fix smspva error 2 code, by retrying with different countries up to 5 times.
2. Fix smspva number banned code, by retrying with different countries to 5 times.
3. Fix when the SMS is never received, by retrying with different countries to 5 times.

Also,

4. reduce the waiting time for SMS from 10 minutes to 2 minutes.

**Comment by leandrosardi** [comment]
# 1. Fix smspva error 2 code, by retrying with different countries up to 5 times

```
Code: (unknown). SmsPva Error: Code 2. Method get_number. Visit http://smspva.com/new_theme_api.html for more information.
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/sms/smspva.rb:179:in `getNumber'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/linkedin/bots/LinkedIn.rb:960:in `signup'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/pampa/mybotprocess.rb:607:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.36/lib/myremoteprocess.rb:111:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/pampa/mybotprocess.rb:796:in `run'
./p/bots.farming.rb:36:in `<main>'
```

**Comment by leandrosardi** [comment]
# 2. Fix smspva number banned code, by retrying with different countries to 5 times

```
Code: (unknown). Phone number is banned!
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/linkedin/bots/LinkedIn.rb:1136:in `signup'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/pampa/mybotprocess.rb:607:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.36/lib/myremoteprocess.rb:111:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.165/lib/pampa/mybotprocess.rb:796:in `run'
./p/bots.farming.rb:36:in `<main>'
```

**Comment by leandrosardi** [comment]
> 1. Fix smspva error 2 code, by retrying with different countries up to 5 times.

Done. Couldn't test this patch, because I couldn't replicate the glitch.

> 2. Fix smspva number banned code, by retrying with different countries to 5 times.

Done. Tested.

> 3. Fix when the SMS is never received, by retrying with different countries to 5 times.

Done. Tested.

> 4. reduce the waiting time for SMS from 10 minutes to 2 minutes.

Done. Tested.
