### ISSUE TITLE
Glitch on IPN processing

### ISSUE THREAD

**Issue by leandrosardi** [ExpandedVenture/ConnectionSphere#276]
This issue started to happen after #273.

## Error

```
2022-05-03 12:13:48: Loading divisions... done (3)
2022-05-03 12:13:48: Processing pending IPNs...
2022-05-03 12:13:48:  > D190B81E-82E1-44CA-881F-602F19D69D82...
2022-05-03 12:13:48:  >  > euler... Error:TinyTds::Error: Cannot update records
on the table movement, because it is a financial-transactions table. Resolve any
 incongruency with new records instead!
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
60:in `do'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
60:in `block (2 levels) in execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/logging.rb:
33:in `log_yield'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
58:in `block in execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `block in synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/thre
aded.rb:99:in `hold'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
32:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
76:in `execute_dui'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:9
61:in `execute_dui'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
07:in `update'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1987:i
n `_update_without_checking'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1974:i
n `_update'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1968:i
n `_update_columns'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1922:i
n `block (2 levels) in _save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1122:i
n `around_update'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1906:i
n `block in _save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1122:i
n `around_save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1892:i
n `_save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:i
n `block (2 levels) in save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:2046:i
n `block in checked_transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/transaction
s.rb:105:in `block in transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `block in synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/thre
aded.rb:99:in `hold'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/transaction
s.rb:97:in `transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:2046:i
n `checked_transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:i
n `block in save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:2034:i
n `checked_save_failure'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:i
n `save'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/move
ment.rb:237:in `expire'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/invo
ice.rb:328:in `block (2 levels) in getPaid'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
92:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
92:in `_all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:4
5:in `all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/invo
ice.rb:326:in `block in getPaid'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
92:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
92:in `_all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:4
5:in `all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/invo
ice.rb:324:in `getPaid'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/buff
erpaypalnotification.rb:333:in `block in process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/transaction
s.rb:134:in `_transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/transaction
s.rb:108:in `block in transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `block in synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/thre
aded.rb:103:in `hold'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/transaction
s.rb:97:in `transaction'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/invoicing_payments_processing-1.1.79/lib/buff
erpaypalnotification.rb:265:in `process'
Y:/views/api1.3/accounting/sync/paypal/notification.erb:52:in `__tilt_20626908'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call
'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `eval
uate'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `rend
er'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `ren
der'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:667:in `erb
'
app.rb:1540:in `block in <main>'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `ca
ll'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `bl
ock in compile!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'

C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `blo
ck (3 levels) in route!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `rou
te_eval'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `blo
ck (2 levels) in route!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `bl
ock in process_route'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `ca
tch'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `pr
ocess_route'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `blo
ck in route!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `eac
h'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `rou
te!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `bl
ock in dispatch!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `bl
ock in invoke'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `ca
tch'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `in
voke'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `di
spatch!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `blo
ck in call!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `bl
ock in invoke'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `ca
tch'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `in
voke'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `cal
l!'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `cal
l'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/xss
_header.rb:18:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/bas
e.rb:49:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/bas
e.rb:49:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/pat
h_traversal.rb:16:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/jso
n_csrf.rb:18:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/bas
e.rb:49:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/bas
e.rb:49:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/fra
me_options.rb:31:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:2
52:in `context'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:2
47:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/logger.rb:15:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/commonlogger.rb:33:in `c
all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `cal
l'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `cal
l'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/methodoverride.rb:22:in
`call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `cal
l'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `ca
ll'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `bl
ock in call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `sy
nchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `ca
ll'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in
`call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle
_request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `proces
s_client'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block
in run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `c
all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `b
lock in spawn_thread'
```

**Comment by leandrosardi** [comment]
Fixed.
