### ISSUE TITLE
Query timeout on planning of followups

### ISSUE THREAD

**Issue by leandrosardi** [ExpandedVenture/ConnectionSphere#280]
In consequence, too many followups are not being created.

## Log

```
2022-05-05 12:58:01:  >  > New Pipeline 0001... error: TinyTds::Error: Adaptive
Server connection timed out
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
218:in `fields'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
218:in `block in fetch_rows'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
63:in `block in execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `block in synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/thre
aded.rb:103:in `hold'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.
rb:249:in `synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
32:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:9
50:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:
217:in `fetch_rows'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:1
39:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:4
5:in `block in all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:8
90:in `_all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:4
5:in `all'
Y:/lib/prospecting/pipeline.rb:572:in `lnusers_involved'
./p/_planner.prospecting.pipeline.followups.rb:64:in `block (2 levels) in plan_f
ollowup_messages'
./p/_planner.prospecting.pipeline.followups.rb:61:in `each'
./p/_planner.prospecting.pipeline.followups.rb:61:in `block in plan_followup_mes
sages'
./p/_planner.prospecting.pipeline.followups.rb:53:in `each'
./p/_planner.prospecting.pipeline.followups.rb:53:in `plan_followup_messages'
./p/_planner.prospecting.pipeline.followups.rb:315:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.42/lib/mylocalprocess.rb:13
1:in `run'
./p/_planner.prospecting.pipeline.followups.rb:332:in `<main>'.
2022-05-05 12:59:02:  >  > Submit to boterrorlog... done
2022-05-05 12:59:03:
2022-05-05 12:59:03:  >  > Update from central (2)... done
2022-05-05 12:59:21:  >  > Update worker (2)... done
2022-05-05 12:59:21:  >  > Sleep... done
2022-05-05 12:59:21: -------------------------------------------
```

**Comment by leandrosardi** [comment]
Fixed.
