### ISSUE TITLE
Issue when scraping inbox.

### ISSUE THREAD

**Issue by leandrosardi** [ExpandedVenture/ConnectionSphere#292]
```
unable to locate element, using {:class=>/msg-conversation-listitem__participant-names/, :tag_name=>"h3"} 
Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:536:in `assert_element_found' 
Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:508:in `assert_exists' 
Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:81:in `text' 
Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.180/lib/linkedin/bots/LinkedInChat.rb:255:in `block in scrape_inbox' 
Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.180/lib/linkedin/bots/LinkedInChat.rb:238:in `each' 
Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.180/lib/linkedin/bots/LinkedInChat.rb:238:in `scrape_inbox' 
lib/prospecting/process.rb:989:in `do' 
Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.180/lib/pampa/mybotprocess.rb:670:in `process' 
Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.43/lib/myremoteprocess.rb:111:in `run' 
Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.180/lib/pampa/mybotprocess.rb:763:in `run' ./p/bots.prospecting.rb:32:in `<main>'
```

**Comment by leandrosardi** [comment]
Issue cannot be replicated.
