### ISSUE TITLE
Same error after scraping the first block

### ISSUE THREAD

**Issue by leandrosardi** [ExpandedVenture/ConnectionSphere#294]
```
2022-05-14 03:48:01: Iterate to page 60... aYes
2022-05-14 03:48:23: Double-checking pagination... 
2022-05-14 03:49:24:  > Reporting failure Net::ReadTimeout. /home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/bots/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:543:in `find_elements_by'
/home/bots/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/locators/element/locator.rb:202:in `wd_find_by_regexp_selector'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/locators/element/locator.rb:110:in `find_first_by_multiple'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/locators/element/locator.rb:88:in `find_first_by_one'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/locators/element/locator.rb:42:in `locate'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:551:in `locate'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:505:in `assert_exists'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:42:in `exists?'
/home/bots/.rvm/gems/ruby-2.2.4/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:425:in `present?'
/home/bots/.rvm/gems/ruby-2.2.4/gems/bots-1.2.180/lib/linkedin/bots/LinkedInSearchSalesNavigator.rb:332:in `noresults?'
/home/bots/.rvm/gems/ruby-2.2.4/gems/bots-1.2.180/lib/linkedin/bots/LinkedInSearchSalesNavigator.rb:377:in `iterate'
/home/bots/code/tempora/lib/listbuilder/process.rb:411:in `block in do'
/home/bots/code/tempora/lib/listbuilder/process.rb:342:in `each'
/home/bots/code/tempora/lib/listbuilder/process.rb:342:in `do'
/home/bots/.rvm/gems/ruby-2.2.4/gems/bots-1.2.180/lib/pampa/mybotprocess.rb:670:in `process'
./listbuilder.rb:128:in `process'
/home/bots/.rvm/gems/ruby-2.2.4/gems/pampa_workers-1.1.43/lib/myremoteprocess.rb:111:in `run'
/home/bots/.rvm/gems/ruby-2.2.4/gems/bots-1.2.180/lib/pampa/mybotprocess.rb:763:in `run'
./listbuilder.rb:147:in `<main>'... done
2022-05-14 03:49:24:  > Tracking bot error... done (with no screenshot)
2022-05-14 03:49:25:  > Should destroy any browsers?... no
2022-05-14 03:49:25:  > Ping to Division... done
2022-05-14 03:49:26:  > Release lnuser... done
2022-05-14 03:49:26:  > Run garbage collector... done
2022-05-14 03:49:26:  > Sleep
```

**Comment by leandrosardi** [comment]
![image](https://user-images.githubusercontent.com/55877846/168443380-c76b6b16-8650-4b26-ba98-d82b2670828d.png)
