### ISSUE TITLE
goto command error

### ISSUE THREAD

**Issue by ExpandedVenture** [ExpandedVenture/ConnectionSphere#51]
```
2021-08-15 09:42:38:  > Notify run start... done
2021-08-15 09:42:38:  > Goto command...
2021-08-15 09:42:38:  >  > Upload goto1 screenshot... filename:Y:/public/clients
/444C3405-1B08-4B81-89AE-F499A9B23D75/crowdtrust/goto1.23007D39-6ED9-4AB7-9E4F-0
6C9CBC8B10E.png:.
error: undefined method `save_screenshot' for nil:NilClass
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.30/lib/browser
factory.rb:867:in `screenshot'
./p/remote.rb:39:in `uploadScreenShot'
./p/remote.rb:326:in `block in process'
./p/remote.rb:230:in `each'
./p/remote.rb:230:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.20/lib/myremoteprocess.rb:1
03:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.30/lib/browser
factory.rb:243:in `run'
./p/remote.rb:528:in `<main>'.
2021-08-15 09:42:38:  >  > Notify run error... done
```

**Comment by ExpandedVenture** [comment]
Done.
